repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
            - --max-line-length=150
            - --extend-ignore=E203,W503
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black